### ISSUE TITLE
karapace service not running

### ISSUE THREAD

**Issue by deusebio** [canonical/karapace-k8s-operator#19]
## Steps to reproduce

1. juju deploy ./bundle.yaml

with bundle.yaml being:

```
bundle: kubernetes
applications:
  consumer:
    charm: kafka-test-app
    channel: latest/edge
    revision: 11
    scale: 1
    options:
      consumer_group_prefix: my-cg
      role: consumer
      topic_name: test-topic
    constraints: arch=amd64
  cruise-controller:
    charm: kafka-k8s
    channel: 3/edge
    revision: 77
    scale: 1
    options:
      roles: balancer
    constraints: arch=amd64
    trust: true
  data-integrator:
    charm: data-integrator
    channel: latest/stable
    revision: 79
    scale: 1
    options:
      consumer-group-prefix: admin-cg
      extra-user-roles: admin
      topic-name: admin-topic
    constraints: arch=amd64
  kafka:
    charm: kafka-k8s
    channel: 3/edge
    revision: 77
    scale: 3
    options:
      profile: testing
    constraints: arch=amd64
    trust: true
  karapace:
    charm: karapace-k8s
    channel: latest/edge
    revision: 4
    scale: 1
    constraints: arch=amd64
  producer:
    charm: kafka-test-app
    channel: latest/edge
    revision: 11
    scale: 1
    options:
      num_messages: 10000000
      partitions: 2
      replication_factor: 3
      role: producer
      topic_name: test-topic
    constraints: arch=amd64
  tls:
    charm: self-signed-certificates
    channel: latest/stable
    revision: 155
    scale: 1
    options:
      ca-common-name: Canonical
    constraints: arch=amd64
  zookeeper:
    charm: zookeeper-k8s
    channel: 3/edge
    revision: 75
    scale: 3
    constraints: arch=amd64
    trust: true
relations:
- - kafka:certificates
  - tls:certificates
- - zookeeper:certificates
  - tls:certificates
- - consumer:certificates
  - tls:certificates
- - producer:certificates
  - tls:certificates
- - kafka:zookeeper
  - zookeeper:zookeeper
- - data-integrator:kafka
  - kafka:kafka-client
- - karapace:certificates
  - tls:certificates
- - karapace:kafka
  - kafka:kafka-client
- - cruise-controller:certificates
  - tls:certificates
- - cruise-controller:peer-cluster
  - kafka:peer-cluster-orchestrator
```

## Expected behavior

The services go all in active/idle state

## Actual behavior

Karapace is in blocked status with message "unit not connected to kafka". The logs from the Karapace Pebble service shows:

```
2025-01-31T20:52:37.517Z [karapace]   File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
2025-01-31T20:52:37.517Z [karapace]     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2025-01-31T20:52:37.517Z [karapace] socket.gaierror: [Errno -8] Servname not supported for ai_socktype
```

Longer log output in the file attached. 

## Versions

Operating system: Ubuntu 22.04

Juju CLI: 3.6.2-genericlinux-amd64

Juju agent: 3.6.2

Charm revision: 4

Microk8s: 1.31-strict/stable

## Log output

Pebble long logs: 

[log.karapace.txt](https://github.com/user-attachments/files/18624204/log.karapace.txt)
